DATA:
  data_root: data/kitti360/kitti360_3d
  classes: 19
  aug: False
  voxel_size: 0.08
  input_color: False
  use_shm: False

TEST:
  arch_3d: MinkUNet34C
  manual_seed: 3407
  split: val  
  test_workers: 4
  test_gpu: [0]
  test_batch_size: 4
  model_path: /gpfs/home/jj1220/FYP/OpenSemantic/out/kitti360/train_3d_backbone/MinkUNet34C/model/model_best.pth.tar
  save_folder:
  test_repeats: 5
  vis_input: False
  vis_pred: True
  vis_gt: True

Distributed:
  dist_url: tcp://127.0.0.1:6787
  dist_backend: 'nccl'
  multiprocessing_distributed: True
  world_size: 1
  rank: 0