DATA:
  data_root: data/kitti360/kitti360_3d
  data_root_2d_fused_feature: data/kitti360/kitti360_multiview_fusion/train
  feature_2d_extractor: openseg
  classes: 19
  aug: True
  voxel_size: 0.1
  input_color: False
  use_shm: False
  
DISTILL:
  arch_3d: MinkUNet34C
  ignore_label: 255
  train_gpu: [0]
  workers: 12 
  batch_size: 1 
  batch_size_val: 1  
  base_lr: 0.0001
  loss_type: cosine 
  loop: 2
  epochs: 100
  start_epoch: 0
  power: 0.9
  momentum: 0.9
  manual_seed: 3407
  print_freq: 10
  save_freq: 1
  save_path:
  resume:
  evaluate: True  
  eval_freq: 1

TEST:
  split: test  
  prompt_eng: True
  mark_no_feature_to_unknown: True
  feature_type: 'ensemble' # 'distill' | 'fusion' | 'ensemble'
  save_feature_as_numpy: False
  vis_pred: False
  vis_gt: False
  test_workers: 8
  test_gpu: [0]
  test_batch_size: 1
  test_repeats: 5
  model_path:
  save_folder:

Distributed:
  dist_url: tcp://127.0.0.1:6788
  dist_backend: 'nccl'
  multiprocessing_distributed: True
  world_size: 1
  rank: 0
