DATA:
  data_root: data/matterport/matterport_3d
  data_root_2d_fused_feature: data/matterport/matterport_multiview_openseg_test
  feature_2d_extractor: openseg
  classes: 21
  aug: True
  voxel_size: 0.02
  input_color: False
  use_shm: False
  
TEST:
  arch_3d: MinkUNet34C
  manual_seed: 3407
  split: test 
  prompt_eng: True
  mark_no_feature_to_unknown: True
  feature_type: 'ensemble' # 'distill' | 'fusion' | 'ensemble'
  save_feature_as_numpy: False
  vis_input: False
  vis_pred: False
  vis_gt: False
  test_workers: 8
  test_gpu: [0]
  test_batch_size: 1
  test_repeats: 10
  model_path: /gpfs/home/jj1220/FYP/OpenSemantic/out/matterport/train_openseg_distill/MinkUNet34C/21/model/model_best.pth.tar
  save_folder:

Distributed:
  dist_url: tcp://127.0.0.1:6787
  dist_backend: 'nccl'
  multiprocessing_distributed: True
  world_size: 1
  rank: 0
